# Generated by Django 4.2.6 on 2023-10-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_productimage_tag_remove_product_comment_product_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='src',
            field=models.ImageField(default=0, upload_to='images'),
        ),
    ]
